sudo: required
services:
  - docker

before_install:
  - docker build -t liraop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run liraop/react-test npm run test -- --coverage

after_success:
  - docker build -t "$DOCKERHUB_ID"/multi-client ./client
  - docker build -t "$DOCKERHUB_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKERHUB_ID"/multi-server ./server
  - docker build -t "$DOCKERHUB_ID"/multi-worker ./worker
  - echo "$DOCKERHUD_PW" | docker login -u "$DOCKERHUB_ID" --pasword-stdin
  - docker push "$DOCKERHUB_ID"/multi-client
  - docker push "$DOCKERHUB_ID"/multi-nginx
  - docker push "$DOCKERHUB_ID"/multi-server
  - docker push "$DOCKERHUB_ID"/multi-worker
