sudo: required
services:
  - docker

before_install:
  - docker build -t "$DOCKERHUB_ID"/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run "$DOCKERHUB_ID"/react-test npm run test -- --coverage

after_success:
  - docker build -t "$DOCKERHUB_ID"/multi-client ./client
  - docker build -t "$DOCKERHUB_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKERHUB_ID"/multi-server ./server
  - docker build -t "$DOCKERHUB_ID"/multi-worker ./worker
  - echo "$DOCKERHUB_PW" | docker login -u "$DOCKERHUB_ID" --password-stdin
  - docker push "$DOCKERHUB_ID"/multi-client:latest
  - docker push "$DOCKERHUB_ID"/multi-nginx:latest
  - docker push "$DOCKERHUB_ID"/multi-server:latest
  - docker push "$DOCKERHUB_ID"/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-420696111632
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: $AWS_Pw
