sudo: required
services:
  - docker

before_install:
  - docker build -t liraop/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run liraop/react-test npm run test -- --coverage

after_success:
  - docker build -t "$DOCKERHUB_ID"/multi-client:latest ./client
  - docker build -t "$DOCKERHUB_ID"/multi-nginx:latest ./nginx
  - docker build -t "$DOCKERHUB_ID"/multi-server:latest ./server
  - docker build -t "$DOCKERHUB_ID"/multi-worker:latest ./worker
  - echo "$DOCKERHUD_PW" | docker login -u "$DOCKERHUB_ID" --pasword-stdin
  - docker push "$DOCKERHUB_ID"/multi-client:latest
  - docker push "$DOCKERHUB_ID"/multi-nginx:latest
  - docker push "$DOCKERHUB_ID"/multi-server:latest
  - docker push "$DOCKERHUB_ID"/multi-worker:latest
